### ISSUE TITLE
Restore exrproxy-env/auto_test/unit_test.py

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#132]
Somehow, `exrproxy-env/auto_test/unit_test.py` got deleted in a previous commit. It needs to be restored from the last commit where it existed, then perhaps updated a bit.

**Comment by pom11** [comment]
`unit_test.py` was converted into `snode_unit_test.py` and `xquery_unit_test.py` and in many other `test` scripts.
