### ISSUE TITLE
XQ hasn't indexed 22 day old Uniswap swaps

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#136]
I'm not  yet certain this is a problem, but it concerns me that XQ has not yet indexed a Uniswap swaps which occurred just 22 days ago (according to Uniswap Analytics):

python3 xq.py --xqlimit 3 --xqpair aBLOCK/ETH --host $VPS4 --projectid f918cfa5-1ca7-4fb2-9d14-075e4b75d5fd --apikey rizCqvd7_L8Lbl3epuNBELRtxQez7IDylp_-aYbc7f4
🔀 XQuery for pair aBLOCK/ETH 
{'data': {'xquery': []}}

Is there a way to check the progress of XQ in indexing Uniswap swaps back to ETH block 13600000 ?

**Comment by pom11** [comment]
this ticket should be on xquery repo
