### ISSUE TITLE
ENH: stateful autobuild/app.py generated docker-compose.yml

### ISSUE THREAD

**Issue by walkjivefly** [blocknetdx/exrproxy-env#144]
Every time `autobuild/app.py` runs it generates all new IP addresses for all targets. This makes it extremely cumbersome to simply add one more target without taking down the entire stack and starting it all up again. 

It is desirable for the script to remember the IP address for each target and always use that address for that target. Then it would be possible to run the script to add (or remove) a target and only need to restart the servicenode container and the new target container when adding a new target to the stack.

**Comment by pom11** [comment]
`builder.py` supports `.known_hosts` file where every external host reference is saved
