### ISSUE TITLE
SNode global install script error with certain docker compose versions

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/exrproxy-env#191]
**To do:** 

- [ ] fix global install script so `docker-compose --version | awk -F'v' '{print $3}'` works for all styles of version numbers

**Update:**
It seems that when docker compose `2.10.2` is installed (latest), the script parses it incorrectly and sees it as `2.1.0.2`. This results in the script warning that the version installed is <`2.3.3`.

**Comment by ConanMishler** [comment]
@shrnkld Huh, I thought this issue was supposed to automatically be closed when https://github.com/blocknetdx/exrproxy-env/pull/193 was merged because I wrote:
```
Fixes issue #191
```
in the description...😕
