### ISSUE TITLE
[Bug] Entering a non-integer for the payment amount in builder.py results in an error

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/exrproxy-env#204]
Entering any **non-integer** value for `tierX_payment_amount` crashes builder.py

Steps to reproduce:
1. during the builder.py process the user is presented with the following question:
`Press enter for 0USD tier1 amount or type a new USD price:`
2. entering any non-integer eg `0.5` results in:
```CRITICAL:root:Exception:
Traceback (most recent call last):
  File "./builder.py", line 243, in <module>
    b['payment_tier1'] = int(tier1) if tier1 !='' else b["payment_tier1"]
ValueError: invalid literal for int() with base 10: '0.5'
Closing...
```

**To do:**
- [x] allow decimals (replacing `int(tierX)`) - a max of 6 decimal places should be enabled for payment amounts eg $0.000001 / 1000 calls

```
tier1 = snode.inquirer.get_input(f'Press enter for {b["payment_tier1"]}USD tier1 amount or type a new USD price:')
					b['payment_tier1'] = int(tier1) if tier1 !='' else b["payment_tier1"]
					tier2 = snode.inquirer.get_input(f'Press enter for {b["payment_tier2"]}USD tier2 amount or type a new USD price:')
					b['payment_tier2'] = int(tier2) if tier2 !='' else b["payment_tier2"]
```

- [x] add the following content to the payment amount form label: `(max two decimal places)`
- [x] show an error message if number of decimals > 6 : 
-- `Please enter a value with a maximum of 6 decimal places`

**QA:**
- [ ] entering a value with <= 6 decimal places should validate ok
- [ ] entering a value with > 6 decimal places should return the error msg

**Comment by ConanMishler** [comment]
@shrnkld  I've tested for this bug in the latest Projects API and it looks like it has been fixed. Shall we go ahead and close it, or do you want to test it yourself first?

**Comment by shrnkld** [comment]
I'll check it too @ConanMishler and close it when i've reviewed it ;)

thanks for the update.
