### ISSUE TITLE
Add Avalanche Indexer to auto deploy

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/exrproxy-env#22]
**To do:** 

- [x] Add option in SNode autobuild tools to auto-deploy Avalanche Indexer alongside SNode
- [x] The option should be called, `XQuery`
- [ ] Build images for all the XQuery microservices that will be deployed in the stack along with the snode.

**Comment by ConanMishler** [comment]
I moved this back to `In Progress` after adding the task to `Build images for all the XQuery microservices that will be deployed in the stack along with the snode.` I think that needs to be done before we can say the auto deploy setup for XQuery is complete.

**Comment by pom11** [comment]
check #60

**Comment by pom11** [comment]
exrproxy-env needs local files from `xquery` repo so the repo should be as a submodule to `exrproxy-env` and we should not build images for microservices
