### ISSUE TITLE
Fix --deploy_eth and --gethexternal options

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/exrproxy-env#23]
**Scenario:**

Currently, neither the `-deploy_eth True` option, nor the `-gethexternal <IP>` option of app.py deploys the XRouter Service, `xrs::eth_passthrough`. 

**To do:**
- [ ] Using either of these flags/options should deploy the "xrs::eth_passthrough" service.

**Comment by leonVrashitov** [comment]
[https://github.com/blocknetdx/exrproxy-env/pull/34](url)
