### ISSUE TITLE
Add support for https based external GETH

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#24]
Currently, `app.py` assumes an external GETH node will be at a URL of the form, `http://<IP-Address>:8545`. But some (rented) external GETH nodes are actually accessed at a URL of the form, `https://<IP-Address>`. No specific port is specified in accessing these external GETH nodes, which means they use the default `https` port, `443`.

Example access to an `https` external GETH node:

`$ curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://loving-benz:getup-tingle-unkind-wiry-pummel-john@nd-876-805-717.p2pify.com
{"jsonrpc":"2.0","id":1,"result":"0xc8b0ff"}`

**Comment by leonVrashitov** [comment]
https://github.com/blocknetdx/eth-payment-processor/blob/master/util/eth_payments.py#L36 
A connection is established by eth-payment-processor. It uses websockets. To add HTTPS we need to refactor eth-payment-processor.

**Comment by ConanMishler** [comment]
Close this issue because it's not longer relevant.
