### ISSUE TITLE
Enhance workflow: BUILD IMAGE FROM TEMPLATE

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#25]
Currently, the BUILD IMAGE FROM TEMPLATE workflow depends on `blockchain-config-files/manifest-latest.json` and the coin config Info found in the `blockchain-config-files/wallet-conf` dir. But this makes it difficult to create an image for a new coin which does not yet have this Info. stored in the `blockchain-config-files` repo. This in turn makes it difficult to test the new coin daemon config files. Although there is a BUILD CUSTOM IMAGE workflow available, that workflow requires creating a new branch and a custom `Dockerfile`, which is a bit of a laborious process.
We could really use an enhancement to the BUILD IMAGE FROM TEMPLATE workflow, which will build the coin image using config info from a branch or fork of the `blockchain-configuration-files` repo, specified by the user as a  URL. 

@walkjivefly has already made the desired enhancements to the BUILD IMAGE FROM TEMPLATE workflow and submitted this PR to merge it: https://github.com/blocknetdx/dockerimages/pull/42. However, he has not yet responded to reviews by @conan and @atcsecure requesting minor changes and squashing/rebasing the many WIP commits. So, though this task is not yet complete, it doesn't seem there is anything for @leo to do on it.

New coins we could use for testing this process include:
HNS
USBL

- [ ] Task completed and tested

**Comment by leo** [comment]
I think you pinged the wrong person!
