### ISSUE TITLE
Fix space after BLOCK in xrouter.conf

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#27]
Autobuild code currently creates `start-snode.sh` code which then creates an `xrouter.conf` file with a line like the following:

`wallets=BLOCK ,BTC,LTC,DGB`

The space character after `BLOCK` is preventing BLOCK from being added to the list of coins supported by XRouter.

**To Do:**

- [x] Remove the space after `BLOCK`

**Comment by leonVrashitov** [comment]
https://github.com/blocknetdx/exrproxy-env/pull/29
