### ISSUE TITLE
Prepare PR to merge autobuild-generatetemplates branch to master

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#47]
- [x] Update all references to `autobuild-generatetemplates` branch in the `master` branch of the `exrproxy-env` repo so they will point to `master` branch instead of `autobuild-generatetemplates` branch.
- [x] Prepare a PR to merge the above updates and also merge `autobuild-generatetemplates` branch of `blockchain-configuration-files` repo to `master`.

**Comment by leonVrashitov** [comment]
https://github.com/blocknetdx/blockchain-configuration-files/pull/134
