### ISSUE TITLE
API call to disable Api-Key header and allow for Project-ID only (Mimics Infura Project Secret)

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/exrproxy-env#53]
more info needed...

**Comment by pom11** [comment]
api-key is needed in headers for XQuery plugin

**Comment by atcsecure** [comment]
not sure this should be closed @pom11  and @shrnkld .

lets re-open and verify if this functionality is needed

**Comment by pom11** [comment]
If we put apikey in url the endpoints will be very long and look strange. Also they could be easily siphoned even if the users uses SSL connection. I purpose to keep them in headers

**Comment by atcsecure** [comment]
@pom11 we aren't looking to adding apikey to URL, that would be a security issue.  This ticket is about just disabling the api-key requirement for a specific project-id (similar to how infura worked)

**Comment by pom11** [comment]
It says *mimics infura secret*, that is in url. Used it in xq development. Pls change the title accordingly

**Comment by pom11** [comment]
If that is the case, it can be easily done.

**Comment by atcsecure** [comment]
> It says mimics infura secret, that is in url. Used it in xq development. Pls change the title accordingly

I don't see that referenced here: https://infura.io/docs/ethereum/json-rpc/eth-call

'''
## JSON-RPC over HTTPS POST
## Replace YOUR-PROJECT-ID with a Project ID from your Infura Dashboard
## You can also replace mainnet with a different supported network
curl https://mainnet.infura.io/v3/YOUR-PROJECT-ID \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}'

'''

**Comment by pom11** [comment]
​https://:INFURA_SECRET@mainnet.infura.io/v3/INFURA_PROJECT

This is what I ve used in xq development.

**Comment by pom11** [comment]
related to `FREE_EVM_PASSTHROUGH` plugin
