### ISSUE TITLE
Build DASH image which syncs fully

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#55]
Just confirmed (2 Nov): The most recent docker image we have for DASH (`v0.15.0.0-staging`) keeps getting stuck on block 1379127. Fully synced DASH should have a block height of > 1565264.

Leo: Feel free to login to my VPS if you want to look at the logs of the stuck DASH container:
```
ssh conan@185.217.127.108
```
CloudChains has a fully synced DASH container, so if we have trouble getting ours to sync fully, we might ask atcsecure for help.

- [ ] Create docker image for DASH which syncs fully - past block 1565264.

**Comment by leonVrashitov** [comment]
Dash image v0.17.0.2
https://hub.docker.com/layers/blocknetdx/dash/v0.17.0.2-staging/images/sha256-302e89021dffc35dd8a3bb4257a170c02413ba4e2a80b4f58ad89a13caf87be2?context=explore
