### ISSUE TITLE
cli custom.yaml builder

### ISSUE THREAD

**Issue by pom11** [blocknetdx/exrproxy-env#76]
add additional QA script and user will have to answer to specific questions to build the `custom.yaml` file to be passed later on to the `app.py` autobuilder.

- [ ] construct flow
- [ ] mandatory points in flow
- [ ] select from predefined answers

**Comment by walkjivefly** [comment]
Not a bad idea, especially as the number of available images increases. Were you thinking of a gazillion command line switches to enable/disable each image, or a long command line interview session or a PyQT (or whatever) noddy GUI with toggles for each image?

**Comment by pom11** [comment]
something like 
![image](https://user-images.githubusercontent.com/60760299/146674405-ea2add7a-fe11-4b97-acca-affefc4fa691.png)

**Comment by walkjivefly** [comment]
In the blockchain-configuration-files repo is a little-used [script](https://github.com/blocknetdx/blockchain-configuration-files/blob/master/autobuild/utils/manifest-management.py) for manifest maintenance. It's in the style of your second example and is a PITA to use. Hence no-one uses it and it's relegated to a siding. A noddy GUI with a toggle for each available image seems like a better idea. Or a gazillion command line switches :-)

Either way we should have an external manifest of the available images and the docker fragments they require. Or perhaps build the list dynamically from the images available in DockerHub? But we'd still need template fragments for the XR_PROXY, ETH etc. I suppose we should have per-coin parameterisation of  image version, config mount dir and data mount dir. Just for completeness ;-)

**Comment by pom11** [comment]
I vote for a CLI GUI with a toggle for each image available. 

We need all of the possible vars hardcoded for now. In a later iteration we can migrate to post them all on a gist.

**Comment by ConanMishler** [comment]
> Either way we should have an external manifest of the available images and the docker fragments they require.
I was thinking `exrproxy-env/autobuild/examples/alldaemons.yaml` could serve that function, at least for now. So @pom11's enhancement idea, which is a great idea and one which @shrnkld will love, will reference `alldaemons.yaml` and extract entries from it based on user input from a CLI GUI.

**Comment by pom11** [comment]
Actually i will do a `.json` file that will serve this purpose @ConanMishler. I want to keep things separate from what we have. In the future the `alldaemons.yaml` will have changes.

**Comment by pom11** [comment]
also will i m thinking of making the cli builder disk size aware and will know if the snode op will have the req for what he wants to build

**Comment by ConanMishler** [comment]
Reposting an opinion here which I already mentioned to @pom11 in a DM convo:
```
I'm not sure why we need to complicate things in the exrproxy-env repo by adding a special `.json` to track which entries in  `alldaemons.yaml` need to be kept for XQuery to work. Why can't we just take care to make sure `alldaemons.yaml` always contains all entries needed to support XQuery, and also contains comments making it clear that those entries MUST NOT BE DELETED if you plan to support XQuery on your SNode?
Remember, no one can change or corrupt `alldaemons.yaml` without getting their PR approved.

**Comment by pom11** [comment]
This tool will not over complicated things. Will be a separate tool that could help newcomers understand what is mandatory or not in the yaml input file and what parameters are available for each entry.

I ll provide a example asap and will work it from there.
