### ISSUE TITLE
delete unused files

### ISSUE THREAD

**Issue by pom11** [blocknetdx/exrproxy-env#82]
delete unused files

- [ ] delete `custom.yaml` usage

pls add others if they are

**Comment by walkjivefly** [comment]
I'm not sure what you're asking. I did think earlier today that custom.yaml belongs in .gitignore. It's part of the documented workflow but doesn't need to be in the repo.

**Comment by pom11** [comment]
i want to clean this repo a bit. we can rename this issue to `move all *documents* yaml to examples folder`
if there is no yaml file passed to `app.py` `custom.yaml` will be used. i want to remove this clause and force the users to construct a yaml file from with data from `examples` dir. 
also i see there are these that are not used:

- [ ] docker-compose.yaml
- [ ] ref-docker-
- [ ] custom.yaml
- [ ] backup folder
- [ ] docker-compose-dev.yaml
- [ ] docker-compose-geth-external.yaml
- [ ] docker-compose.yaml
