### ISSUE TITLE
Add testnet Trading Node

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#85]
Currently, the `custom.yaml` can be configured to deploy 3 different types of nodes:

1. A regular Service Node is deployed with a `custom.yaml` entry like this:
```
- name: SNODE
```
2. A Service Node running on Blocknet testnet is deployed with an entry like this:
```
- name: testSNODE
```
3. A Trading Node is deployed with an entry like this:
```
- name: TNODE
```
But one important type of node is missing from this list: a Trading Node running on Blocknet testnet. We need `app.py` to recognize the following entry and "do the right thing:"
```
- name: testTNODE
```
- [x] Coded
- [x] Tested

**Comment by walkjivefly** [comment]
I've already done most of this. Testing it now

**Comment by walkjivefly** [comment]
All done and dusted.
